name: touristop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  google_sign_in: ^5.3.3
  # hive
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  # utils
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  http: ^0.13.4
  # state manager
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.0.15
  # map
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.8
  flutter_polyline_points: ^1.0.0
  # widgets
  syncfusion_flutter_datepicker: ^20.1.60
  loading_indicator: ^3.1.0
  dropdown_button2: ^1.6.2
  roundcheckbox: ^2.0.4+1
  flutter_rating_bar: ^4.0.1
  simple_time_range_picker: ^0.0.4
  flutter_tts: ^3.4.0
  flutter_slidable: ^1.3.0
  flutter_dash_nullsafety: ^1.0.0
  # app
  flutter_launcher_icons: ^0.9.3
  animated_splash_screen: ^1.2.0
  introduction_screen: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # hive
  build_runner: ^2.1.11
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/touristop_icon.png"
