name: touristop
description: Capstone Project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  google_sign_in: ^5.3.2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.6
  flutter_riverpod: ^1.0.4
  syncfusion_flutter_datepicker: ^20.1.58
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.10
  dropdown_button2: ^1.5.2
  roundcheckbox: ^2.0.4+1
  flutter_rating_bar: ^4.0.1
  introduction_screen: ^3.0.2
  flutter_dash_nullsafety: ^1.0.0
  flutter_slidable: ^1.3.0
  http: ^0.13.4
  flutter_polyline_points: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
